
CREATE DATABASE IF NOT EXISTS INVENTARIO_DB
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE INVENTARIO_DB;

CREATE TABLE IF NOT EXISTS CATEGORIAS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION TEXT NOT NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS productos (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORIA_ID INT,
    NOMBRE VARCHAR(255) NOT NULL,
    DESCRIPCION TEXT NOT NULL,
    PRECIO DECIMAL(10, 2) NOT NULL,
    STOCK INT NOT NULL,
    SKU VARCHAR(100) NOT NULL UNIQUE,
    ACTIVO TINYINT(1) NOT NULL DEFAULT 1,
    CREATED_AT DATETIME NOT NULL DEFAULT NOW(),
    UPDATED_AT DATETIME NOT NULL DEFAULT NOW() ON UPDATE NOW(),

    CONSTRAINT fk_categoria
        FOREIGN KEY (categoria_id)
        REFERENCES categorias (id)
        ON DELETE SET NULL
);
