USE INVENTARIO_DB;

-- ──────────────────────────────────────────────────────────
-- SP: SP_AGREGAR_PRODUCTO
-- ──────────────────────────────────────────────────────────
DROP PROCEDURE IF EXISTS SP_AGREGAR_PRODUCTO;
DELIMITER $$
CREATE PROCEDURE SP_AGREGAR_PRODUCTO(
    IN P_NOMBRE VARCHAR(255),
    IN P_DESCRIPCION TEXT,
    IN P_PRECIO DECIMAL(10, 2),
    IN P_STOCK INT,
    IN P_CATEGORIA VARCHAR(100),
    IN P_SKU VARCHAR(100)
)
BEGIN
    DECLARE V_CAT_ID INT DEFAULT NULL;

    IF P_CATEGORIA IS NOT NULL AND P_CATEGORIA != '' THEN
        SELECT ID INTO V_CAT_ID
        FROM CATEGORIAS
        WHERE NOMBRE = P_CATEGORIA
        LIMIT 1;

        IF V_CAT_ID IS NULL THEN
            INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES (P_CATEGORIA, '');
            SET V_CAT_ID = LAST_INSERT_ID();
        END IF;
    END IF;

    INSERT INTO PRODUCTOS (CATEGORIA_ID, NOMBRE, DESCRIPCION, PRECIO, STOCK, SKU)
    VALUES (
        V_CAT_ID,
        P_NOMBRE,
        P_DESCRIPCION,
        P_PRECIO,
        P_STOCK,
        IFNULL(P_SKU, CAST(UUID_SHORT() AS CHAR))
    );

    SELECT P.ID, P.NOMBRE, P.DESCRIPCION, P.PRECIO, P.STOCK,
           C.NOMBRE AS CATEGORIA, P.SKU, P.ACTIVO, P.CREATED_AT, P.UPDATED_AT
    FROM PRODUCTOS P
    LEFT JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
    WHERE P.ID = LAST_INSERT_ID();
END$$
DELIMITER ;


-- ──────────────────────────────────────────────────────────
-- SP: SP_LISTAR_PRODUCTOS
-- ──────────────────────────────────────────────────────────
DROP PROCEDURE IF EXISTS SP_LISTAR_PRODUCTOS;
DELIMITER $$
CREATE PROCEDURE SP_LISTAR_PRODUCTOS(
    IN P_LIMITE INT,
    IN P_CATEGORIA VARCHAR(100)
)
BEGIN
    SET P_LIMITE = IFNULL(P_LIMITE, 50);

    IF P_CATEGORIA IS NOT NULL THEN
        SELECT P.ID, P.NOMBRE, P.DESCRIPCION, P.PRECIO,
               P.STOCK, C.NOMBRE AS CATEGORIA, P.SKU,
               P.ACTIVO, P.CREATED_AT, P.UPDATED_AT
        FROM PRODUCTOS P
        LEFT JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
        WHERE C.NOMBRE = P_CATEGORIA AND P.ACTIVO = 1
        ORDER BY P.NOMBRE
        LIMIT P_LIMITE;
    ELSE
        SELECT P.ID, P.NOMBRE, P.DESCRIPCION, P.PRECIO,
               P.STOCK, C.NOMBRE AS CATEGORIA, P.SKU,
               P.ACTIVO, P.CREATED_AT, P.UPDATED_AT
        FROM PRODUCTOS P
        LEFT JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
        WHERE P.ACTIVO = 1
        ORDER BY P.NOMBRE
        LIMIT P_LIMITE;
    END IF;
END$$
DELIMITER ;


-- ──────────────────────────────────────────────────────────
-- SP: SP_BUSCAR_PRODUCTO
-- ──────────────────────────────────────────────────────────
DROP PROCEDURE IF EXISTS SP_BUSCAR_PRODUCTO;
DELIMITER $$
CREATE PROCEDURE SP_BUSCAR_PRODUCTO(
    IN P_ID INT,
    IN P_NOMBRE VARCHAR(255)
)
BEGIN
    IF P_ID IS NOT NULL THEN
        SELECT P.ID, P.NOMBRE, P.DESCRIPCION, P.PRECIO,
               P.STOCK, C.NOMBRE AS CATEGORIA, P.SKU,
               P.ACTIVO, P.CREATED_AT, P.UPDATED_AT
        FROM PRODUCTOS P
        LEFT JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
        WHERE P.ID = P_ID;
    ELSE
        SELECT P.ID, P.NOMBRE, P.DESCRIPCION, P.PRECIO,
               P.STOCK, C.NOMBRE AS CATEGORIA, P.SKU,
               P.ACTIVO, P.CREATED_AT, P.UPDATED_AT
        FROM PRODUCTOS P
        LEFT JOIN CATEGORIAS C ON P.CATEGORIA_ID = C.ID
        WHERE P.NOMBRE LIKE CONCAT('%', P_NOMBRE, '%')
        ORDER BY P.NOMBRE;
    END IF;
END$$
DELIMITER ;


-- ──────────────────────────────────────────────────────────
-- SP: SP_ACTUALIZAR_PRODUCTO
-- ──────────────────────────────────────────────────────────
DROP PROCEDURE IF EXISTS SP_ACTUALIZAR_PRODUCTO;
DELIMITER $$
CREATE PROCEDURE SP_ACTUALIZAR_PRODUCTO(
    IN P_ID INT,
    IN P_NOMBRE VARCHAR(255),
    IN P_DESCRIPCION TEXT,
    IN P_PRECIO DECIMAL(10, 2),
    IN P_STOCK INT,
    IN P_CATEGORIA VARCHAR(100),
    IN P_SKU VARCHAR(100)
)
BEGIN
    DECLARE V_CAT_ID INT DEFAULT NULL;

    IF P_CATEGORIA IS NOT NULL AND P_CATEGORIA != '' THEN
        SELECT ID INTO V_CAT_ID
        FROM CATEGORIAS
        WHERE NOMBRE = P_CATEGORIA
        LIMIT 1;

        IF V_CAT_ID IS NULL THEN
            INSERT INTO CATEGORIAS (NOMBRE, DESCRIPCION) VALUES (P_CATEGORIA, '');
            SET V_CAT_ID = LAST_INSERT_ID();
        END IF;
    END IF;

    UPDATE PRODUCTOS
    SET
        NOMBRE = IFNULL(P_NOMBRE, NOMBRE),
        DESCRIPCION = IFNULL(P_DESCRIPCION, DESCRIPCION),
        PRECIO = IFNULL(P_PRECIO, PRECIO),
        STOCK = IFNULL(P_STOCK, STOCK),
        CATEGORIA_ID = CASE WHEN P_CATEGORIA IS NOT NULL THEN V_CAT_ID ELSE CATEGORIA_ID END,
        SKU = IFNULL(P_SKU, SKU)
    WHERE ID = P_ID;

    -- Devolver filas afectadas + registro actualizado
    SELECT ROW_COUNT() AS AFECTADOS;
END$$
DELIMITER ;


-- ──────────────────────────────────────────────────────────
-- SP: SP_ELIMINAR_PRODUCTO
-- ──────────────────────────────────────────────────────────
DROP PROCEDURE IF EXISTS SP_ELIMINAR_PRODUCTO;
DELIMITER $$
CREATE PROCEDURE SP_ELIMINAR_PRODUCTO(
    IN P_ID INT
)
BEGIN
    DECLARE V_NOMBRE VARCHAR(255) DEFAULT NULL;

    SELECT NOMBRE INTO V_NOMBRE
    FROM PRODUCTOS
    WHERE ID = P_ID
    LIMIT 1;

    IF V_NOMBRE IS NOT NULL THEN
        UPDATE PRODUCTOS SET ACTIVO = 0 WHERE ID = P_ID;
        SELECT V_NOMBRE AS NOMBRE_ELIMINADO, ROW_COUNT() AS AFECTADOS;
    ELSE
        SELECT NULL AS NOMBRE_ELIMINADO, 0 AS AFECTADOS;
    END IF;
END$$
DELIMITER ;
